const siteConfig = {
  name: "Car Rental Budva",
  tagline: "The Adriatic Riviera at your own pace",
  domain: "carrentalbudva.com",
  phone: "",
  email: "info@carrentalbudva.com",
  address: "Tabacina BB, Kotor, 85330",

  hero: {
    headline: "Rent a Car in Budva",
    subheadline: "The Riviera base, beach towns, fortress walls, Venetian old towns and Sveti Stefan all inside a 30-minute drive.",
    image: "/img/hero-budva.webp",
  },

  cars: [
    {
      id: 1,
      slug: "vw-polo",
      typeGroup: "economy",
      name: "VW Polo",
      category: "Economy",
      tagline: "Compact German hatch for Old Town parking and Riviera day-hops",
      lede: "A small hatchback that handles Budva's Old Town lanes, the Slovenska pay-bays, and the coast road as far as Sveti Stefan without breaking a sweat.",
      price: 25,
      image: "/img/fleet/vw-polo.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Air Conditioning", "Bluetooth Audio", "USB Charging", "Central Locking"],
      details: {
        engine: "1.0 L TSI 3-cyl turbo petrol",
        power: "95 hp",
        consumption: "5.2 L/100 km",
        bootSize: "351 L",
        length: "4,074 mm",
        topSpeed: "187 km/h",
        acceleration: "10.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Couples on a week-long Riviera stay", "Solo travellers", "Short Sveti Stefan day-trips"],
      suitability: "Two travellers with cabin bags anchored in Budva for five to ten days, Polo parks everywhere, costs little to fuel, and handles the coast road comfortably.",
      regional: "Slips into the Slovenska Plaža street zones that cost €1–2/h in summer, threads the narrow access road to Kamenovo, and sits at 110 km/h on the E80 toward Bar without complaint.",
    },
    {
      id: 2,
      slug: "renault-clio",
      typeGroup: "economy",
      name: "Renault Clio",
      category: "Economy",
      tagline: "The default Budva Riviera multi-day hatch, cheap to fuel, easy on summer parking",
      lede: "Most common Riviera rental. Five doors, 391 L boot, built for the Jaz–Petrovac week.",
      price: 28,
      image: "/img/fleet/renault-clio.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Bluetooth Audio", "USB Charging", "Central Locking", "Touchscreen Display"],
      details: {
        engine: "1.0 TCe 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.3 L/100 km",
        bootSize: "391 L",
        length: "4,050 mm",
        topSpeed: "188 km/h",
        acceleration: "11.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: true,
      bestFor: ["First-time Riviera visitors", "Couples", "Week-long coastal stays"],
      suitability: "Two travellers working a ten-day Budva base with daily hops to Sveti Stefan, Petrovac, Bečići and a Kotor side-trip mid-week.",
      regional: "Fits the TQ Plaza underground and Slovenska hour-pay zones, threads the single-lane run down to Pržno, and holds cruise at 110 km/h on the Sozina approach without drama.",
    },
    {
      id: 3,
      slug: "citroen-c3",
      typeGroup: "economy",
      name: "Citroen C3",
      category: "Economy",
      tagline: "Softest-riding supermini in the Budva fleet, the patched-tarmac absorber",
      lede: "Advanced Comfort suspension and padded seats, the small car that smothers the Paštrovići back road.",
      price: 27,
      image: "/img/fleet/citroen-c3.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Advanced Comfort Seats", "Bluetooth Audio", "USB Charging", "Lane Departure Warning"],
      details: {
        engine: "1.2 PureTech 3-cyl petrol",
        power: "83 hp",
        consumption: "5.5 L/100 km",
        bootSize: "300 L",
        length: "3,996 mm",
        topSpeed: "175 km/h",
        acceleration: "13.7s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Comfort-first long-stay renters", "Older travellers", "Inland back-road cruisers"],
      suitability: "A couple on a two-week Riviera stay who would rather cruise than carve, the C3 is the gentlest small car for the mixed tarmac above Petrovac and Paštrovići.",
      regional: "The soft damping flatters the cracked bitumen on the spur to Kosmač Fortress and the loop up to Praskvica Monastery; a little underpowered on the long climb to Cetinje but unruffled at riviera cruise speeds.",
    },
    {
      id: 4,
      slug: "peugeot-308",
      typeGroup: "midsize",
      name: "Peugeot 308",
      category: "Mid-Size",
      tagline: "Diesel auto mid-size for the multi-day Riviera-to-Dubrovnik loop",
      lede: "Quiet BlueHDi, 412 L boot, 8-speed EAT auto, the family-of-four default for distance weeks.",
      price: 38,
      image: "/img/fleet/peugeot-308.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Automatic Transmission", "Adaptive Cruise", "Dual-Zone Climate", "Large Boot"],
      details: {
        engine: "1.5 BlueHDi 4-cyl diesel",
        power: "130 hp",
        consumption: "4.4 L/100 km",
        bootSize: "412 L (1,309 L seats folded)",
        length: "4,367 mm",
        topSpeed: "206 km/h",
        acceleration: "10.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 8-spd auto",
      },
      popular: false,
      bestFor: ["Families of four on ten-day Riviera stays", "Cross-border drivers", "Airport-to-coast transfers"],
      suitability: "Four adults or a family of four anchoring in Budva and running a Dubrovnik side-trip, a day at Skadar and a Durmitor weekend from the same base.",
      regional: "Settles at 1,800 rpm on the Sozina tunnel climb, cruises the E65 past Sveti Stefan without breaking sweat, and covers the 90-minute Debeli Brijeg run to Dubrovnik on a fraction of a tank.",
    },
    {
      id: 5,
      slug: "renault-megane",
      typeGroup: "midsize",
      name: "Renault Megane",
      category: "Mid-Size",
      tagline: "Biggest-boot mid-size, wagon-of-luggage room for a fortnight in Bečići",
      lede: "434-litre square boot and a quiet 1.5 dCi diesel, distance-eater tuned for soft ride.",
      price: 36,
      image: "/img/fleet/renault-megane.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Large Boot", "Bluetooth Audio", "Cruise Control", "Parking Sensors"],
      details: {
        engine: "1.5 Blue dCi 4-cyl diesel",
        power: "115 hp",
        consumption: "4.3 L/100 km",
        bootSize: "434 L",
        length: "4,360 mm",
        topSpeed: "195 km/h",
        acceleration: "11.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 6-spd manual",
      },
      popular: false,
      bestFor: ["Families with full-size cases", "Long Riviera stays", "Multi-stop coast itineraries"],
      suitability: "Four travellers on a two-week Budva base who want the biggest boot in the mid-size class for beach gear, pushchair and a weekly Voli shop all loaded at once.",
      regional: "The 434 L boot swallows beach umbrella, two folding chairs, snorkel kit and the airport cases for four on the Tivat run; 6th-gear diesel cruise at 100 km/h is unfussed on the long push to Skadar Lake.",
    },
    {
      id: 6,
      slug: "kia-stonic",
      typeGroup: "suv",
      name: "Kia Stonic",
      category: "Compact Crossover",
      tagline: "Raised-ride compact for Paštrovići back roads and inland day-trips",
      lede: "Higher hip-point than a hatch, 352 L boot, 1.0 turbo petrol, the in-between spec for mixed weeks.",
      price: 40,
      image: "/img/fleet/kia-stonic.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Raised Ride Height", "Apple CarPlay", "Reversing Camera", "Lane Keep Assist"],
      details: {
        engine: "1.0 T-GDi 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.5 L/100 km",
        bootSize: "352 L (1,155 L seats folded)",
        length: "4,140 mm",
        topSpeed: "183 km/h",
        acceleration: "10.7s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Couples heading inland", "Mixed coast-and-mountain weeks", "Budget crossover renters"],
      suitability: "A couple on a seven-to-ten-day Riviera base who plan at least two inland day-trips, Cetinje, Ostrog via Sozina, or the Paštrovići highlands, and want a higher driving position than a hatch.",
      regional: "The higher ride helps on the broken bitumen between Petrovac and Buljarica, the gravel spur to Kosmač viewpoint, and the patched sections of the old road above Rafailovići that a Clio crashes through.",
    },
    {
      id: 7,
      slug: "vw-golf",
      typeGroup: "midsize",
      name: "VW Golf",
      category: "Mid-Size",
      tagline: "DSG diesel benchmark, the quietest long-drive cruiser in the Budva fleet",
      lede: "150 hp 2.0 TDI with 7-spd DSG, 381 L boot, the rational default for mixed coast and inland weeks.",
      price: 42,
      image: "/img/fleet/vw-golf.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["DSG Automatic", "Adaptive Cruise", "Digital Cockpit", "Apple CarPlay"],
      details: {
        engine: "2.0 L TDI diesel (Mk8)",
        power: "150 hp",
        consumption: "4.3 L/100 km",
        bootSize: "381 L (1,237 L seats folded)",
        length: "4,287 mm",
        topSpeed: "223 km/h",
        acceleration: "8.4s (0–100 km/h)",
        driveType: "Front-wheel drive, 7-spd DSG auto",
      },
      popular: false,
      bestFor: ["Couples on mixed coast + inland weeks", "Quiet-cabin seekers", "Tivat Airport arrivals"],
      suitability: "Two or three adults who want Polo-grade city agility and long-drive refinement in the same car, for a ten-day Budva stay that mixes Riviera days with Cetinje, Ostrog and a Dubrovnik run.",
      regional: "Threads the Budva ring-road at school-run pace and settles at 120 km/h on the Sozina tunnel approach to Bar; the DSG picks the right ratio on the Cetinje switchbacks before you think about it.",
    },
  ],

  features: [
    { icon: "map-pin", title: "Budva Town Pickup", description: "Meet us at Budva's Slovenska Plaza promenade, inside the Old Town walls, or at your Riviera hotel. Tivat Airport pickup available, 20 km and 30 minutes away." },
    { icon: "shield-check", title: "Riviera-Ready Insurance", description: "CDW, third-party liability and theft protection on every rental. Zero-excess upgrade available, useful on the tight Old Town lanes and the coastal road's blind corners." },
    { icon: "clock", title: "24/7 Beach-Town Support", description: "Late returns from Sveti Nikola, a puncture on the Paštrovići hairpins, a festival at Jaz, we pick up the phone at any hour." },
    { icon: "ban", title: "Transparent Prices", description: "No coast-season premium on the confirmation page. The rate you book is the rate you pay, taxes, airport fees and mileage already inside." },
    { icon: "refresh-cw", title: "Flexible Cancellation", description: "Weather turns, flights change, plans shift. Cancel most vehicles free up to seven days before pickup." },
    { icon: "globe", title: "Cross-Border Cover", description: "Croatia via Debeli Brijeg, Albania via Božaj, Bosnia through Sutorina, Green Card paperwork sorted at booking time." },
  ],

  testimonials: [
    { name: "Matteo & Giulia", location: "Bari, Italy", text: "Took the ferry from Bari to Bar, picked up a Polo in Budva the next morning. Did Sveti Stefan, Petrovac, and Ada Bojana over four days. The cabrio upgrade was worth every cent on the coastal road. Smooth return, no surprise charges.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "Niamh O'Sullivan", location: "Cork, Ireland", text: "Flew Dublin-Tivat for a ten-day riviera trip. Based in Bečići. Drove the whole coast from Herceg Novi to Ulcinj over the week. A Fiat 500 was perfect, easy parking at every beach stop. Reliable car, honest pricing.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "The Lindqvist Family", location: "Gothenburg, Sweden", text: "Needed a seven-seater for a family of six plus luggage. The Transporter was waiting at Tivat Airport in twenty minutes. Budva for a week, with day trips to Kotor and Sveti Stefan. Kids loved the cabrio afternoon we rented on the last day as a treat.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "Can I drop off in Tivat or Kotor?", a: "Yes, one-way rentals to Tivat Airport (20 km) and Kotor (22 km) are standard. A small one-way fee applies." },
    { q: "What do I bring to pick up the car?", a: "A valid driving licence, passport or ID, and a credit card in the lead driver's name. Non-Latin-script licences need an International Driving Permit alongside." },
    { q: "Where can I park in Budva Old Town?", a: "Cars are not allowed inside the Old Town walls. Use the underground TQ Plaza car park (5-minute walk to the Citadel) or the Slovenska Plaza street zones. Most Riviera hotels include guest parking, confirm at booking." },
    { q: "How old do I need to be?", a: "21 years with at least two years of driving experience. Drivers 21-24 pay a young-driver surcharge that varies by car class." },
    { q: "Is beach parking included?", a: "Rental includes the car and the usual taxes, not parking. Budva has metered street zones and some paid beach car parks (€1-3/hour). We'll brief you on what to expect at pickup." },
    { q: "What about cross-border driving?", a: "Croatia, Albania, Bosnia, Serbia and Kosovo are all supported with Green Card insurance. Let us know at booking which countries you plan to cross." },
    { q: "Is the Sveti Stefan road open to my rental?", a: "Yes, the E65 Adriatic highway runs past Sveti Stefan viewpoints. No restriction on rental cars, free pull-offs above the island." },
    { q: "Summer-season price premium?", a: "No, the price we quote is the price you pay, year-round. July-August availability is tight though, so book early." },
    { q: "Is a deposit required?", a: "Most vehicles hold €100-€350 on a credit card. Some economy options are deposit-free, look for the 'no deposit' filter in the search results." },
    { q: "Is there a mileage limit?", a: "Most rentals are unlimited mileage. Budget economy vehicles sometimes cap at 200 km/day, visible before you confirm." },
    { q: "What about festivals on Jaz Beach?", a: "Sea Dance and similar summer festivals draw crowds. Book the car at least a week in advance if arriving for a festival, and expect full car parks near the beach." },
    { q: "Do you meet late flights at Tivat?", a: "Every arriving flight, no surcharge. Hand over the paperwork, the car's in the terminal lot, done in fifteen minutes." },
    { q: "Can I rent without a credit card?", a: "A few economy models accept debit with a larger deposit. Filter for 'no credit card required' at booking." },
  ],

  locations: [
    { name: "Budva", tag: "Most Popular" },
    { name: "Tivat Airport", tag: "Airport Pickup" },
    { name: "Bečići", tag: "" },
    { name: "Sveti Stefan", tag: "" },
    { name: "Petrovac", tag: "" },
    { name: "Rafailovići", tag: "" },
  ],

  destinations: [
    { name: "Mogren Beach", slug: "blog/mogren-beach-dukley-tunnel", tag: "5 min walk", desc: "Two hidden coves joined by a cliff tunnel, just north of the Old Town.", image: "/img/blog-mogren-beach-dukley-tunnel.webp" },
    { name: "Miločer Park", slug: "blog/milocer-park-villa", tag: "10 min drive", desc: "Royal summer park with umbrella pines and views of Sveti Stefan.", image: "/img/blog-milocer-park-villa.webp" },
    { name: "Drobni Pijesak", slug: "blog/drobni-pijesak-cove", tag: "15 min drive", desc: "A fine-sand cove with a Paštrovići assembly history.", image: "/img/blog-drobni-pijesak-cove.webp" },
    { name: "Reževići Monastery", slug: "blog/rezevici-monastery", tag: "20 min drive", desc: "An 800-year-old Nemanjić foundation above the Riviera.", image: "/img/blog-rezevici-monastery.webp" },
    { name: "Lovćen Mausoleum", slug: "blog/budva-to-lovcen-mausoleum", tag: "90 min drive", desc: "Njegoš's tomb at 1,657 m on the summit of Mount Lovćen.", image: "/img/blog-budva-to-lovcen-mausoleum.webp" },
    { name: "Cetinje", slug: "blog/cetinje-day-trip-from-budva", tag: "1 hr inland", desc: "Montenegro's old royal capital, palaces, museums, monastery.", image: "/img/blog-cetinje-day-trip-from-budva.webp" },
    { name: "Stari Bar", slug: "blog/sutomore-stari-bar-ruins", tag: "50 min south", desc: "A medieval ruined city on a hillside above Bar.", image: "/img/blog-sutomore-stari-bar-ruins.webp" },
    { name: "Kotor", slug: "blog/kotor-day-trip-from-budva", tag: "30 min drive", desc: "The walled old town and the climb to San Giovanni fortress.", image: "/img/blog-kotor-day-trip-from-budva.webp" },
  ],
};

export default siteConfig;
